version: "2"
checks:
  file-lines:
    config:
      threshold: 1500
  method-complexity:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 500
exclude_patterns:
- "cypress/"
- "**/node_modules/"
- "temp/"
- "test/"
- "**/*.d.ts"
- "**/*.js"